Set github secret for the PAT to clone the k8s repo

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -482,8 +482,14 @@ jobs:
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
 
       - name: Clone k8s repository
+        env:
+          GITHUB_TOKEN_K8S: ${{ secrets.DIGITAL_STEP_FLOW_GITHUB_TOKEN }}
         run: |
-          git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/pucrs-tcc-digital-step-flow-frontend-k8s.git k8s-repo
+          if [ -z "${GITHUB_TOKEN_K8S}" ]; then
+            echo "ERROR: DIGITAL_STEP_FLOW_GITHUB_TOKEN secret is not set." >&2
+            exit 1
+          fi
+          git clone "https://x-access-token:${GITHUB_TOKEN_K8S}@github.com/${{ github.repository_owner }}/pucrs-tcc-digital-step-flow-frontend-k8s.git" k8s-repo
 
       - name: Setup k8s repository for dev
         working-directory: ./k8s-repo
